### ISSUE TITLE
Error fetching github user and repository

### ISSUE THREAD

**Issue by clemtibs** [fgrehm/previewdocs#5]
I installed the linux amd64 binary to my path, made it executable, and ran it in my repository root. I got the following messages:

```
± previewdocs
2014/05/31 21:37:42 WARNING: ACCESS_TOKEN was not found, you'll be subject to GitHub's Rate Limiting of 60 requests per hour. Please read http://developer.github.com/v3/#rate-limiting for more information
2014/05/31 21:37:43 Error fetching github user and repository
ERROR: exit status 1
2014/05/31 21:37:43 Listening on port 8888
```

Navigating to http://localhost:8888/docs on my browser yeilds: `Invalid repository 'docs'`

I'm not quite sure why previewdocs needs to to be fetching a remote repository when it's meant for previewing local changes on my hard drive? Did I misunderstand? Do I need to commit the changes locally first before it can preview them? Also, my "project" name is docs at the moment, so my path looks like '/docs/docs'. Would that confuse it perhaps?

**Comment by fgrehm** [comment]
The thing is that viewdocs works with a github repo and username and the default template requires that information to work properly, I parse that information from the remote github origin.

I'm up for discussing alternatives, maybe we should support a CLI option to make things work without a remote origin?

**Comment by clemtibs** [comment]
Forgive my not being able to understand the GO source itself. But are you saying that the preview actually needs to pull the remote repo to serve it locally? In my use-case, I was building an entire doc suite from scratch before I even had a remote repo to push it to, so I was expecting previewdocs to just be a local go server that simply hosted the current directory with the same methods and layout that viewdocs was doing so that I could just refresh my browser with the preview as I wrote and saved files. I think this is the true nature of a "preview" so that one can be free from the hastle of pushing/waiting/capping github rate limiting altogether. Perhaps an easy change would be to look for a local repo in stead of a remote one and just do everything else the same?

**Comment by fgrehm** [comment]
> Forgive my not being able to understand the GO source itself. But are you saying that the preview actually needs to pull the remote repo to serve it locally?

No! Sorry if I wasn't clear, previewdocs just need to know whats your github username and repository and for that it currently [uses `git config --get remote.origin.url`](https://github.com/fgrehm/previewdocs/blob/349b9f92115e87cd80e17ffd52ab3836a63bca8d/previewdocs.go#L126), there is no need to push the code back to github, you just need to `git remote add origin git@github.com:your-user/your-repo.git` and that message is likely to go away :-)

**Comment by clemtibs** [comment]
ahh. It just needs the name of the remote repo to piece together the URL huh?

**Comment by fgrehm** [comment]
@brianclements yup!

**Comment by clemtibs** [comment]
Finally had a chance to test this. Turns out my issue was that I like to use the name "github" for my github remote names instead of "origin". Thus why it didn't work. Perhaps you can add an error message for the user to check for that? Or even just cut to the chase and scan for whatever remotes exist and pick one, or like you said which is best, specify at runtime what the name of the remote is.

**Comment by fgrehm** [comment]
@brianclements thanks for the info :-)

Just to keep things focused I've opened GH-6 and GH-7 to take care of the issues we discussed here. Please LMK if you run into other problems!
